import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
    await prisma.facility.createMany({
        data: [
            {
                name: 'すなみの湯',
                description:
                    'タトゥー可（小さめのワンポイントは問題なし）',
                prefecture: '東京都',
                city: '新宿区',
                address: '歌舞伎町1-1',
                isTattooOk: true,
                tags: '温泉,サウナ',
                latitude: 35.6938,
                longitude: 139.7034,
                source: 'seed',
                status: 'approved',
                price: '1,100円〜',
                bathTypes: JSON.stringify({
                    '男湯': { temperature: 42, capacity: 96 },
                    '女湯': { temperature: 41, capacity: 91 },
                    '露天': { temperature: 40, capacity: 30 },
                }),
                facilities: JSON.stringify(['24時間営業', 'Wi-Fi', '駐車場', '露天風呂スペース', '食事処', '作業スペース']),
                paymentMethods: JSON.stringify(['現金', 'クレジットカード', '電子マネー']),
                towelOptions: JSON.stringify(['レンタルフェイスタオル有料', 'レンタルバスタオル有料', '館内着', 'サウナマットビート板']),
                amenities: JSON.stringify(['シャンプー', 'カミソリ', 'コンディショナー', 'ボディソープ', 'ナイロンタオル', 'ドライヤー']),
                relaxation: JSON.stringify(['ボディケア', 'アカスリ', 'タイ古式', 'ヘッドスパ']),
            },
            {
                name: 'しろかぜサウナ',
                description: '要確認だが基本的にタトゥーOKの方針',
                prefecture: '東京都',
                city: '渋谷区',
                address: '渋谷2-2',
                isTattooOk: true,
                tags: 'サウナ,温浴',
                latitude: 35.6595,
                longitude: 139.7005,
                source: 'seed',
                status: 'approved',
                price: '1,200円',
                bathTypes: JSON.stringify({
                    'サウナ': { temperature: 95, capacity: 50 },
                    '水風呂': { temperature: 15, capacity: 20 },
                }),
            },
            {
                name: 'みなと湯',
                description: '家族経営の温泉。タトゥーは小さめなら可',
                prefecture: '東京都',
                city: '港区',
                address: '港1-3',
                isTattooOk: true,
                tags: '温泉',
                latitude: 35.6586,
                longitude: 139.7454,
                source: 'seed',
                status: 'approved',
                openingHours: '10:00〜23:00',
                closedDays: '年中無休',
                phone: '03-0000-0001',
                website: 'https://example.com/minatoyu',
                price: '1,100円',
                bathTypes: JSON.stringify({
                    '男湯': { temperature: 42, capacity: 80 },
                    '女湯': { temperature: 42, capacity: 75 },
                }),
            },
            {
                name: 'あかねの湯',
                description: '露天風呂とサウナあり。タトゥーは要相談',
                prefecture: '東京都',
                city: '世田谷区',
                address: '世田谷4-5',
                isTattooOk: false,
                tags: '温泉,露天',
                latitude: 35.6467,
                longitude: 139.6532,
                source: 'seed',
                status: 'approved',
                openingHours: '11:00〜24:00',
                closedDays: '毎週水曜日',
                phone: '03-0000-0002',
                website: 'https://example.com/akanenoyu',
                price: '1,300円',
                bathTypes: JSON.stringify({
                    '男湯': { temperature: 43, capacity: 100 },
                    '女湯': { temperature: 42, capacity: 95 },
                    '露天': { temperature: 40, capacity: 40 },
                }),
            },
            {
                name: 'ねむの湯',
                description: '貸切風呂あり。タトゥー可',
                prefecture: '東京都',
                city: '目黒区',
                address: '目黒2-8',
                isTattooOk: true,
                tags: '温泉,家族風呂',
                latitude: 35.6411,
                longitude: 139.6982,
                source: 'seed',
                status: 'approved',
                openingHours: '9:00〜22:00',
                closedDays: '第2火曜日',
                phone: '03-0000-0003',
                website: 'https://example.com/nemunoyu',
                price: '1,000円〜',
                bathTypes: JSON.stringify({
                    '男湯': { temperature: 41, capacity: 60 },
                    '女湯': { temperature: 41, capacity: 60 },
                    '貸切': { temperature: 42, capacity: 4 },
                }),
            },
            {
                name: 'はなれサウナ',
                description: '静かな個室サウナ。タトゥー可',
                prefecture: '東京都',
                city: '中野区',
                address: '中野3-9',
                isTattooOk: true,
                tags: 'サウナ,個室',
                latitude: 35.7074,
                longitude: 139.6639,
                source: 'seed',
                status: 'approved',
                price: '1,500円',
                bathTypes: JSON.stringify({
                    '個室1': { temperature: 90, capacity: 2 },
                    '個室2': { temperature: 85, capacity: 3 },
                    '水風呂': { temperature: 16, capacity: 8 },
                }),
            },
            {
                name: 'ほしの湯',
                description: 'サウナ小屋と水風呂が人気',
                prefecture: '東京都',
                city: '墨田区',
                address: '業平1-1',
                isTattooOk: true,
                tags: '温泉,サウナ',
                latitude: 35.7101,
                longitude: 139.8089,
                source: 'seed',
                status: 'approved',
            },
            {
                name: 'ゆらら温泉',
                description: '温泉と岩盤浴あり。タトゥーは要確認',
                prefecture: '東京都',
                city: '江東区',
                address: '東陽2-6',
                isTattooOk: false,
                tags: '温泉,岩盤浴',
                latitude: 35.6733,
                longitude: 139.8176,
                source: 'seed',
                status: 'approved',
            },
            {
                name: 'ふるさと湯',
                description: '昔ながらの銭湯型温泉。タトゥーは小さめ可',
                prefecture: '東京都',
                city: '台東区',
                address: '浅草1-5',
                isTattooOk: true,
                tags: '銭湯,温泉',
                latitude: 35.7148,
                longitude: 139.7967,
                source: 'seed',
                status: 'approved',
            },
            {
                name: 'かぜのサウナ',
                description: '都会の中のサウナ。短時間プランあり',
                prefecture: '東京都',
                city: '豊島区',
                address: '池袋3-4',
                isTattooOk: true,
                tags: 'サウナ',
                latitude: 35.7295,
                longitude: 139.7101,
                source: 'seed',
                status: 'approved',
            },
            {
                name: 'おもて湯',
                description: '観光客にも人気。タトゥーは事前連絡推奨',
                prefecture: '東京都',
                city: '中央区',
                address: '日本橋2-2',
                isTattooOk: false,
                tags: '温泉,観光',
                latitude: 35.6824,
                longitude: 139.7745,
                source: 'seed',
                status: 'approved',
            },
            {
                name: 'さくらサウナ',
                description: '女性専用時間帯あり。タトゥー可',
                prefecture: '東京都',
                city: '渋谷区',
                address: '恵比寿1-2',
                isTattooOk: true,
                tags: 'サウナ,女性専用',
                latitude: 35.6467,
                longitude: 139.7093,
                source: 'seed',
                status: 'approved',
            },
            {
                name: 'まちの温泉',
                description: '地域密着型。リーズナブル',
                prefecture: '東京都',
                city: '板橋区',
                address: '板橋4-4',
                isTattooOk: false,
                tags: '温泉,地域',
                latitude: 35.7512,
                longitude: 139.705,
                source: 'seed',
                status: 'approved',
            },
            {
                name: 'こもれびの湯',
                description: '自然光の入る露天が魅力',
                prefecture: '東京都',
                city: '練馬区',
                address: '練馬5-3',
                isTattooOk: true,
                tags: '温泉,露天',
                latitude: 35.7356,
                longitude: 139.6529,
                source: 'seed',
                status: 'approved',
            },
            {
                name: 'ひるまサウナ',
                description: '昼割プランあり。タトゥー可',
                prefecture: '東京都',
                city: '台東区',
                address: '上野2-3',
                isTattooOk: true,
                tags: 'サウナ,割引',
                latitude: 35.712,
                longitude: 139.7752,
                source: 'seed',
                status: 'approved',
            },
            {
                name: 'みやこ温泉',
                description: '温泉と簡易宿泊あり',
                prefecture: '東京都',
                city: '江戸川区',
                address: '小岩1-1',
                isTattooOk: false,
                tags: '温泉,宿泊',
                latitude: 35.733,
                longitude: 139.876,
                source: 'seed',
                status: 'approved',
            },
            {
                name: 'なごみサウナ',
                description: 'アットホームなサウナ。タトゥー可',
                prefecture: '東京都',
                city: '葛飾区',
                address: '亀有3-7',
                isTattooOk: true,
                tags: 'サウナ,地域',
                latitude: 35.7462,
                longitude: 139.8637,
                source: 'seed',
                status: 'approved',
            },
            // --- 埼玉県のテストデータ ---
            {
                name: 'さいたま湯処',
                description: '埼玉市内の温泉施設。タトゥーは事前確認推奨',
                prefecture: '埼玉県',
                city: 'さいたま市',
                address: '中央区1-1',
                isTattooOk: false,
                tags: '温泉,家族風呂',
                latitude: 35.8617,
                longitude: 139.6455,
                source: 'seed',
                status: 'approved',
                price: '900円〜',
            },
            {
                name: 'かわぐちサウナハウス',
                description: '24時間営業のサウナ。短時間プランあり。タトゥー可',
                prefecture: '埼玉県',
                city: '川口市',
                address: '川口2-2',
                isTattooOk: true,
                tags: 'サウナ,個室',
                latitude: 35.8050,
                longitude: 139.7179,
                source: 'seed',
                status: 'approved',
                price: '1,200円',
            },
            {
                name: '川越いこいの湯',
                description: '観光地に近い温泉。露天あり。タトゥーは小さめ可',
                prefecture: '埼玉県',
                city: '川越市',
                address: '川越本町3-5',
                isTattooOk: true,
                tags: '温泉,露天',
                latitude: 35.9247,
                longitude: 139.4856,
                source: 'seed',
                status: 'approved',
                price: '1,100円',
            },
            // --- 神奈川県のテストデータ ---
            {
                name: '横浜みなと湯',
                description: '横浜駅近くの温浴施設。タトゥーは要確認だが比較的緩め',
                prefecture: '神奈川県',
                city: '横浜市',
                address: '西区みなと1-1',
                isTattooOk: false,
                tags: '温泉,観光',
                latitude: 35.4437,
                longitude: 139.6380,
                source: 'seed',
                status: 'approved',
                price: '1,300円',
            },
            {
                name: 'かわさきサウナプラザ',
                description: '川崎駅近くの大箱サウナ。多目的施設で外来利用歓迎',
                prefecture: '神奈川県',
                city: '川崎市',
                address: '川崎区駅前2-3',
                isTattooOk: true,
                tags: 'サウナ,大型',
                latitude: 35.5308,
                longitude: 139.7036,
                source: 'seed',
                status: 'approved',
                price: '1,400円',
            },
            {
                name: '鎌倉露天処',
                description: '鎌倉の海沿いにある露天風呂。景色が良い',
                prefecture: '神奈川県',
                city: '鎌倉市',
                address: '由比ヶ浜4-2',
                isTattooOk: false,
                tags: '温泉,露天,観光',
                latitude: 35.3197,
                longitude: 139.5500,
                source: 'seed',
                status: 'approved',
                price: '1,600円',
            },
        ],
        skipDuplicates: true,
    })
}

main()
    .catch(e => {
        console.error(e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
